# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        # E501 = line too long
        # W503 = line break before binary operator
        # E203 = whitespace before ':' (conflicts with black)
        args: ["--ignore=E501,E203"]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: local
    # Continuous integration checks
    hooks:
      - id: tests-runner
        name: Testing Runner
        entry: bash -c 'runner/run_tests.sh'
        language: system
        pass_filenames: false
        always_run: true
      - id: tests-builder
        name: Testing Builder
        entry: bash -c 'builder/run_tests.sh'
        language: system
        pass_filenames: false
        always_run: true
      - id: tests-nodemapper
        name: Testing Nodemapper
        entry: bash -c 'nodemapper/run_tests.sh'
        language: system
        pass_filenames: false
        always_run: true
      - id: tests-electron-app
        name: Testing Electron App
        entry: bash -c 'electron-app/run_tests.sh'
        language: system
        pass_filenames: false
        always_run: true
      - id: tests-backend
        name: Testing Backend
        entry: bash -c 'backend/run_tests.sh'
        language: system
        pass_filenames: false
        always_run: true
