configfile: "config/config.yaml"

params = config["params"]

rule copy:
    input:
        list(map(workflow.source_path,
            expand(
                "../results/{indir}/{filename}",
                indir=config["input_namespace"],
                filename=params["filename"],
            )
        ))
    output:
        expand(
            "results/{outdir}/{filename}",
            outdir=config["output_namespace"],
            filename=params["filename"],
        )
    shell:
        """
        cp {input} {output}
        """
