"ports":
- "ref": "payload_run$in"
  "label": "in (payload_run)"
  "namespace": "in"
  "mapping":
  - "module": "payload_run"
    "port": "in"
"namespace": "payload_run"
"payload_run":
  "name": "payload_run"
  "type": "module"
  "snakefile": "/Users/jsb/repos/jsbrittain/GRAPEVNE/electron-app/postbuild_tests/test-repo/workflows/single_modules/sources/payload_run/workflow/Snakefile"
  "config":
    "params":
      "filename": "data.csv"
    "ports":
    - "ref": "in"
      "label": "in"
      "namespace": "in"
    "namespace": "payload_run"
