[tool.ruff]
lint.ignore = ["E501"]

[tool.poetry]
name = "runner"
version = "0.3.1"
description = "GRAPEVNE Runner"
authors = ["Kraemer-lab"]
license = "MIT"
readme = "README.md"
exclude = [
    "runner/snakemake_runner_test",
]

[tool.poetry.dependencies]
python = "^3.11"
appdirs = "1.4.4"
attrs = "23.1.0"
builder = {path = "../builder"}
certifi = "2023.7.22"
charset-normalizer = "3.1.0"
configargparse = "1.5.3"
connection-pool = "0.0.3"
datrie = "0.8.2"
docutils = "0.21.2"
dpath = "2.1.6"
exceptiongroup = "1.1.1"
fastjsonschema = "2.17.1"
gitdb = "4.0.10"
gitpython = "3.1.41"
humanfriendly = "10.0"
idna = "3.7"
iniconfig = "2.0.0"
jinja2 = "3.1.4"
jsonschema = "4.17.3"
jupyter-core = "5.3.1"
markupsafe = "2.1.3"
nbformat = "5.9.0"
packaging = "23.1"
plac = "1.3.5"
platformdirs = "3.7.0"
pluggy = "1.0.0"
psutil = "5.9.5"
pulp = "2.7.0"
pyrsistent = "0.19.3"
pyyaml = "6.0.1"
requests = "2.32.2"
reretry = "0.11.8"
smart-open = {version = "6.3.0", extras = ["all"]}
smmap = "5.0.0"
snakemake = "7.32"
stopit = "1.1.2"
tabulate = "0.9.0"
throttler = "1.2.2"
tomli = "2.0.1"
toposort = "1.10"
traitlets = "5.9.0"
urllib3 = "2.0.7"
wrapt = "1.15.0"
yte = "1.5.1"


[tool.poetry.group.dev.dependencies]
ruff = "0.3.0"
pytest = "7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
