name: electron-app

on:
  workflow_call:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: electron-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v2
      - name: Run tests
        run: |
          ./build_deps.sh
          ./run_tests.sh
