name: Flake8-backend

on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/flake8.yml'
    - 'backend/**'
    - '!backend/README.md'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Testing code with flake8
      run: |
        flake8 $(git ls-files '*.py')
