name: GRAPEVNE

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  es-lint-nodemapper:
    uses: ./.github/workflows/eslint-nodemapper.yml
  jest-nodemapper:
    uses: ./.github/workflows/jest-nodemapper.yml
  es-lint-electron-app:
    uses: ./.github/workflows/eslint-electron-app.yml
  jest-electron-app:
    uses: ./.github/workflows/jest-electron-app.yml
  flake8-backend:
    uses: ./.github/workflows/flake8-backend.yml
  pytest-backend:
    uses: ./.github/workflows/pytest-backend.yml
  flake8-builder:
    uses: ./.github/workflows/flake8-builder.yml
  pytest-builder:
    uses: ./.github/workflows/pytest-builder.yml
  flake8-runner:
    uses: ./.github/workflows/flake8-runner.yml
  pytest-runner:
    uses: ./.github/workflows/pytest-runner.yml
