name: Nightly
on:
  workflow_dispatch:
  schedule:
    - cron: "37 04 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: check_last_run
        with:
          route: GET /repos/${{github.repository}}/actions/workflows/nightly.yml/runs?per_page=1&status=completed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo Last nightly build: ${{ fromJson(steps.check_last_run.outputs.data).workflow_runs[0].head_sha }}"
    outputs:
      last_sha: ${{ fromJson(steps.check_last_run.outputs.data).workflow_runs[0].head_sha }}

  build_ubuntu:
    name: Build Ubuntu
    needs: [check]
    if: needs.check.outputs.last_sha != github.sha
    permissions: write-all
    uses: ./.github/workflows/nightly_build.yml
    with:
      os: ubuntu-latest
    secrets: inherit

  build_windows:
    name: Build Windows
    needs: [check]
    if: needs.check.outputs.last_sha != github.sha
    permissions: write-all
    uses: ./.github/workflows/nightly_build.yml
    with:
      os: windows-latest
    secrets: inherit

  build_macos14:
    name: Build macOS-14
    needs: [check]
    if: needs.check.outputs.last_sha != github.sha
    permissions: write-all
    uses: ./.github/workflows/nightly_build.yml
    with:
      os: macos-14
    secrets: inherit

  # Separate macOS-12 and macOS-14 builds to avoid signing conflicts
  # (https://github.com/kraemer-lab/GRAPEVNE/issues/243)
  build_macos12:
    name: Build macOS-12
    needs: [check, build_macos14]
    if: needs.check.outputs.last_sha != github.sha
    permissions: write-all
    uses: ./.github/workflows/nightly_build.yml
    with:
      os: macos-12
    secrets: inherit
