name: phyloflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  es-lint:
    uses: ./.github/workflows/eslint.yml
  jest:
    uses: ./.github/workflows/jest.yml
  flake8-backend:
    uses: ./.github/workflows/flake8-backend.yml
  pytest-backend:
    uses: ./.github/workflows/pytest-backend.yml
  flake8-builder:
    uses: ./.github/workflows/flake8-builder.yml
  pytest-builder:
    uses: ./.github/workflows/pytest-builder.yml
  flake8-runner:
    uses: ./.github/workflows/flake8-runner.yml
  pytest-runner:
    uses: ./.github/workflows/pytest-runner.yml
