name: Post-build checks
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: "138.0.7204.243"
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: build
          miniforge-version: latest
          auto-update-conda: true
          auto-activate-base: true
          python-version: "3.13"
          use-mamba: true
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v2
      - name: install MacOS (M1) build dependencies
        shell: bash -el {0}  # required to sustain the conda environment
        run: |
          if [ "$RUNNER_OS" == "macOS" ] && [ "$RUNNER_ARCH" == "ARM64" ]; then
            brew install pango
          fi
      # setuptools needs to be available globally for the yarn build script
      - name: Install setuptools
        shell: bash -el {0}  # required to sustain the conda environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
      - name: build
        working-directory: ./electron-app
        shell: bash -el {0}  # required to sustain the conda environment
        run: |
          corepack enable
          ./build_deps.sh
          yarn install
          yarn
          yarn build
          yarn package
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: tmate debugging
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: postbuild-tests
        working-directory: ./electron-app
        shell: bash -el {0}  # required to sustain the conda environment
        run: |
          ./run_postbuild_tests.sh
