name: Publish
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  build_ubuntu:
    name: Build ubuntu
    permissions: write-all
    uses: ./.github/workflows/publish_build.yml
    with:
      os: ubuntu-latest
    secrets: inherit

  build_windows:
    name: Build windows
    permissions: write-all
    uses: ./.github/workflows/publish_build.yml
    with:
      os: windows-latest
    secrets: inherit

  build_macos:
    name: Build macOS
    permissions: write-all
    uses: ./.github/workflows/publish_build.yml
    with:
      os: macos-latest
    secrets: inherit
