name: Publish
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: publish
        working-directory: ./electron-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        # 'yarn package' is only run to allow build_testsuite.sh to run before
        # the package is pushed for publishing ('yarn run publish' builds and
        # publishes in one step)
        run: |
          ./build_deps.sh
          yarn
          yarn build
          yarn package && ./build_testsuite.sh
          #yarn run publish
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
