name: Publish
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  build_ubuntu:
    name: Build ubuntu
    permissions: write-all
    uses: ./.github/workflows/publish_build.yml
    with:
      os: ubuntu-latest
    secrets: inherit

  build_windows:
    name: Build windows
    permissions: write-all
    uses: ./.github/workflows/publish_build.yml
    with:
      os: windows-latest
    secrets: inherit

  build_macos14:
    name: Build macOS-14
    permissions: write-all
    uses: ./.github/workflows/publish_build.yml
    with:
      os: macos-14
    secrets: inherit

  # Separate macOS-12 and macOS-14 builds to avoid signing conflicts
  # (https://github.com/kraemer-lab/GRAPEVNE/issues/243)
  build_macos12:
    name: Build macOS-12
    needs: [build_macos14]
    permissions: write-all
    uses: ./.github/workflows/publish_build.yml
    with:
      os: macos-12
    secrets: inherit
