name: Publish
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 20
    - name: publish
      working-directory: ./electron-app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./run_build_deps.sh
        yarn
        yarn build
        yarn run publish
