name: Pytest-runner

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: runner
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install
      - name: Testing code with pytest
        run: |
          poetry run pytest
